version: "3.7"

services:
  ocs:
    image: golang:latest
    container_name: ocs
    tty: true
    command: /bin/bash
    ports:
      - 38085:38085
    volumes:
      - ./:/ocs/
    working_dir: /ocs




