version: "3.7"

services:
  ocs:
    image: golang:latest
    container_name: ocs
    tty: true
    command: /bin/bash
    ports:
      - 38085:38085
    volumes:
      - ./:/ocs/
    working_dir: /ocs



  postgres:
      image: bitnami/postgresql:14.5.0
      container_name: postgres_ocs
      restart: always
      environment:
          - POSTGRESQL_USERNAME=root
          - POSTGRESQL_PASSWORD=root
          - POSTGRESQL_DATABASE=ocs
      ports:
      - 5438:5432
      volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data

  redis:
      image: redis
      container_name: redis_ocs
      ports:
          - 6378:6379
      restart: always